
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: student-depression-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: "1"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: student-depression-web
    depends_on:
      - backend
    ports:
      - "8001:80"
    volumes:
      - ./static:/usr/share/nginx/html
    environment:
      - API_BASE=http://localhost:8000